// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB03ftPXa1YmmzySq9U1MkeomMbBD1KGJ0',
    appId: '1:458259510432:web:5690cc754ddcfbef2445c5',
    messagingSenderId: '458259510432',
    projectId: 'avinya-17d9d',
    authDomain: 'avinya-17d9d.firebaseapp.com',
    storageBucket: 'avinya-17d9d.appspot.com',
    measurementId: 'G-B2E744C7J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAkl2DZCkbHxs4fwFGK11VVfc61PFG68g',
    appId: '1:458259510432:android:0735c09c19a850622445c5',
    messagingSenderId: '458259510432',
    projectId: 'avinya-17d9d',
    storageBucket: 'avinya-17d9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnqrK99D9kbFKpXGw8y-2nOQGuoB-m01Y',
    appId: '1:458259510432:ios:62056aa5aada78b82445c5',
    messagingSenderId: '458259510432',
    projectId: 'avinya-17d9d',
    storageBucket: 'avinya-17d9d.appspot.com',
    iosClientId: '458259510432-6rr5m2nsvhkv7vd2kfhj9o3gaa4vcogl.apps.googleusercontent.com',
    iosBundleId: 'com.example.avinyaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnqrK99D9kbFKpXGw8y-2nOQGuoB-m01Y',
    appId: '1:458259510432:ios:62056aa5aada78b82445c5',
    messagingSenderId: '458259510432',
    projectId: 'avinya-17d9d',
    storageBucket: 'avinya-17d9d.appspot.com',
    iosClientId: '458259510432-6rr5m2nsvhkv7vd2kfhj9o3gaa4vcogl.apps.googleusercontent.com',
    iosBundleId: 'com.example.avinyaapp',
  );
}
